### ISSUE TITLE
`PyodidePlugin is not a constructor` error

### ISSUE THREAD

**Issue by federicofernandez** [pyodide/pyodide-webpack-plugin#20]
I'm trying to set up a webpack project with the Pyodide WebPack Plugin v1.2.0 (Pyodide 0.24.1) but I'm getting this error when starting the project:

```
[webpack-cli] TypeError: PyodidePlugin is not a constructor
    at module.exports (/Library/WebServer/Documents/citycompass/webpack.config.js:103:6)
    at loadConfigByPath (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/webpack-cli.js:1445:37)
    at WebpackCLI.loadConfig (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/webpack-cli.js:1515:38)
    at WebpackCLI.createCompiler (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/webpack-cli.js:1781:22)
    at Command.<anonymous> (/Library/WebServer/Documents/citycompass/node_modules/@webpack-cli/serve/lib/index.js:81:30)
    at Command.parseAsync (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at Command.<anonymous> (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
    at Command.parseAsync (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at WebpackCLI.run (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/webpack-cli.js:1360:9)
    at runCLI (/Library/WebServer/Documents/citycompass/node_modules/webpack-cli/lib/bootstrap.js:9:9)
error Command failed with exit code 2.
```

I installed the plugin with this command:

`yarn add -D pyodide @pyodide/webpack-plugin`

And including it in the webpack configuration in this way:

```
    const PyodidePlugin = require("@pyodide/webpack-plugin");
    plugins: [
            new PyodidePlugin(),
```

Any clue?

**Comment by mneil** [comment]
Hi @federicofernandez I think this is already addressed in #17 . Barrel import syntax should resolve the issue

```
const { PyodidePlugin } = require("@pyodide/webpack-plugin");
```

That should be updated in the docs :). I will keep this open to track that the documentation should change. Let me know if this resolves your issue.

**Comment by federicofernandez** [comment]
Thanks a lot @mneil !

That solved the issue. 

Now I'm facing another problems, but it might be due to my lack of knowledge of the webpack configuration, probably not related to the plugin:

```
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

Thanks again!

**Comment by federicofernandez** [comment]
Just in case it helps others, it looks like it is a problem with `node-fetch` that has a bug in v3. Downgrading to v2 seems to fix the issue.

Now facing new problems:

```
WARNING in ./node_modules/pyodide/pyodide.js 1:297-304
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by federicofernandez** [comment]
Also tried activating the option for a global `loadPyodide`:

```
            new PyodidePlugin({ globalLoadPyodide: true }),
```

Is that the right syntax?

And then trying to use it as:

```
        let pyodide = await globalThis.loadPyodide();
```

**Comment by federicofernandez** [comment]
This is the full warning:

```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (/Library/WebServer/Documents/citycompass/node_modules/webpack/lib/dependencies/ContextDependency.js:109:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Library/WebServer/Documents/citycompass/node_modules/webpack/lib/Compilation.js:3140:24)
    at /Library/WebServer/Documents/citycompass/node_modules/webpack/lib/Compilation.js:2737:28
    at eval (eval at create (/Library/WebServer/Documents/citycompass/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:29:1)
    at /Library/WebServer/Documents/citycompass/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:380:10
    at /Library/WebServer/Documents/citycompass/node_modules/neo-async/async.js:2830:7
    at Object.each (/Library/WebServer/Documents/citycompass/node_modules/neo-async/async.js:2850:39)
    at /Library/WebServer/Documents/citycompass/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:356:17
    at /Library/WebServer/Documents/citycompass/node_modules/neo-async/async.js:2830:7
    at Object.each (/Library/WebServer/Documents/citycompass/node_modules/neo-async/async.js:2850:39)
    at /Library/WebServer/Documents/citycompass/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:50:15
    at Hook.eval [as callAsync] (eval at create (/Library/WebServer/Documents/citycompass/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Library/WebServer/Documents/citycompass/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/Library/WebServer/Documents/citycompass/node_modules/webpack/lib/Compilation.js:2722:28)
    at /Library/WebServer/Documents/citycompass/node_modules/webpack/lib/Compiler.js:1186:19
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
 @ ./src/index.js 15:15-33
```

**Comment by mneil** [comment]
This seems like maybe you are using esm modules and mixing require with import syntax? Or maybe something with node 20 that I haven't messed with yet?

The dependency stack is just a warning. It's annoying, but I would venture to guess it could be related to modules.

If you are using modules then you could try importing it like this instead
```
import { PyodidePlugin } from "@pyodide/webpack-plugin"
```

For the loadPyodide issue you can either expose it globally (which you did) or include it like:

```
const loadPyodide = require("pyodide")
// or for esm
// import loadPyodide from "pyodide"
```

**Comment by federicofernandez** [comment]
Thanks a lot @mneil. I'll try downgrading `node` and check what you say about the modules.

I'll let you know how it goes. Thanks again.

**Comment by federicofernandez** [comment]
The call to `pyodide` happens now, there is an error about the Fetch API (`URL scheme "webpack" is not supported.`), but for sure not related to the plug-in. Thanks again @mneil for your help.

**Comment by federicofernandez** [comment]
It looks like webpack is not taking into account the plugin, because I get the error message about URL scheme not supported, both with and without the plug-in. Calling directly a script with `node` in the `CLI` works well in terms of being able to call `pyodide`.

```
Fetch API cannot load webpack://olympic-district-simulation/./node_modules/pyodide/pyodide.asm.wasm. URL scheme "webpack" is not supported.
```

**Comment by mneil** [comment]
Thanks for reporting. I'm realizing the docs could be definitely be improved and the plugin needs to be a bit smarter to handle changes better from pyodide upstream. A few patches are failing on the latest version. However, that shouldn't block you.

Try setting the indexURL when you call `loadPyodide`

```javascript
const pyodide = await loadPyodide({
    indexURL: `${window.location.origin}/pyodide`
});
```

**Comment by federicofernandez** [comment]
Michael, thanks a lot for your help. I tried setting the `indexURL` and then copying the pyodide files to the relevant places, but, no, same issue. Still blocked. I'll let you know if I discover something on my end. Thanks again!

**Comment by federicofernandez** [comment]
Thanks a lot for following this issue, Michael. I'll try that new approach! Thanks again.
