### ISSUE TITLE
UnhandledSchemeError

### ISSUE THREAD

**Issue by Aaronius** [pyodide/pyodide-webpack-plugin#23]
I installed this plugin as described in the readme and I started seeing the following warnings and errors when running a webpack build:

```
WARNING in ./node_modules/node-domexception/index.js 5:31-56
Module not found: Error: Can't resolve 'worker_threads' in '/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/node-domexception'
 @ ./node_modules/fetch-blob/from.js 3:0-44 86:16-28
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/pyodide/pyodide.mjs
 @ ./src/index.tsx 4:0-38 7:22-33

WARNING in ./node_modules/pyodide/pyodide.mjs 9:1996-2005
Critical dependency: the request of a dependency is an expression
 @ ./src/index.tsx 4:0-38 7:22-33

WARNING in ./node_modules/pyodide/pyodide.mjs 9:2140-2149
Critical dependency: the request of a dependency is an expression
 @ ./src/index.tsx 4:0-38 7:22-33

WARNING in ./node_modules/pyodide/pyodide.mjs 9:2385-2416
Critical dependency: the request of a dependency is an expression
 @ ./src/index.tsx 4:0-38 7:22-33

4 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in node:buffer
Module build failed: UnhandledSchemeError: Reading from "node:buffer" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:835:8)
    at processResource (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:825:3)
    at NormalModule.build (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:969:15)
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/Compilation.js:1377:12
    at NormalModule.needBuild (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:1257:32)
    at Compilation._buildModule (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/Compilation.js:1358:10)
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:282:12)
    at process.processImmediate (node:internal/timers:476:21)
 @ ./node_modules/node-fetch/src/index.js 13:0-35 375:20-31 396:29-43 401:5-19 402:5-19
 @ ./node_modules/pyodide/pyodide.mjs
 @ ./src/index.tsx 4:0-38 7:22-33

ERROR in node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:835:8)
    at processResource (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
    at iteratePitchingLoaders (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
    at runLoaders (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
    at NormalModule._doBuild (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:825:3)
    at NormalModule.build (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:969:15)
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/Compilation.js:1377:12
    at NormalModule.needBuild (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/NormalModule.js:1257:32)
    at Compilation._buildModule (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/Compilation.js:1358:10)
    at /Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (/Users/aaronhardy/dev/demos/pyodide-demo/node_modules/webpack/lib/util/AsyncQueue.js:282:12)
    at process.processImmediate (node:internal/timers:476:21)
 @ ./node_modules/fetch-blob/from.js 1:0-68 8:17-19 14:46-54 34:46-54 88:12-28
 @ ./node_modules/node-fetch/src/index.js 27:0-34:28 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68 37:0-68
 @ ./node_modules/pyodide/pyodide.mjs
 @ ./src/index.tsx 4:0-38 7:22-33
```

Plus several more UnhandledSchemeError errors related to `node:*`. Have you seen this before? I'm on webpack@5.89.0, @pyodide/webpack-plugin@1.2.0, and pyodide@0.24.1.

**Comment by Aaronius** [comment]
I just noticed @federicofernandez [encountered the same issue](https://github.com/pyodide/pyodide-webpack-plugin/issues/20#issuecomment-1771834322). Downgrading node-fetch to 2.x solved the error.

**Comment by mneil** [comment]
Version 1.3.0 was released a couple minutes ago. Upgrading to that should resolve the issue.

**Comment by Aaronius** [comment]
That did fix it. It fixed all the warnings as well. Thank you!
